### PR TITLE
Tutorial week 4

### PR DESCRIPTION
**Pull request by drumslayert**

### CODE REVIEW

**Comment by drumslayert** [comment]
https://github.com/TIY-Durham/2015-FALL-FEE/issues/370

**Comment by jeremyrist** [comment]
:+1:  Thanks for the mocha tutorial! Well done. I think _Tools with Terry_ needs a logo and everything man

**Comment by cmauban** [comment]
Nice topping it off with some test examples! :+1:

**Comment by karjac14** [comment]
superb tutorial! I agree with Jeremy, This tutorial needs a logo! :+1:

**Pull request merged**
