### PR TITLE
my specs skitches

### PR DESCRIPTION
**Pull request by drumslayert**
my stitches are in here by accident

### CODE REVIEW

**Comment by karjac14** [comment]
looks great, you missed some text elements, but I guess thats something can be figured when doing the actual html and css. :+1:

**Comment by drumslayert** [comment]
https://github.com/TIY-Durham/2015-FALL-FEE/issues/400

**Comment by Ricecoder** [comment]
So many skitches! Good work on adding html elements and some possible JS events. :+1:

**Comment by drumslayert** [comment]
great work! :+1:

**Pull request merged**
