### PR TITLE
rough tutorial week 3

### PR DESCRIPTION
**Pull request by drumslayert**
accidentally edited my tutorial in master so Im pulling it into journal week 3 branch.

### CODE REVIEW

**Comment by drumslayert** [comment]
https://github.com/TIY-Durham/2015-FALL-FEE/issues/271

**Comment by ShayHall** [comment]
Let's play find the typo in the first paragraph game: 

> Today you will leanr how to color your font! 

This next line would be better with some tics around the code 

> Once you decide on a font you love, in your CSS styles sheet just set your font-family: to your favorite pick like so: font-family: sans-serif;

Other than my pickiness, this is a good introduction to coloring fonts :heavy_check_mark:

**Comment by ShayHall** [comment]
And where's your journal entry?

**Comment by rosalsm** [comment]
I love that movie too but it is very sad. Terry add some ```` in your text so we can see it better!  :)

**Pull request merged**
