### PR TITLE
Updated journal week 2

### PR DESCRIPTION
**Pull request by drumslayert**

### CODE REVIEW

**Comment by rosalsm** [comment]
I am glad you left the panic zone to go to a better place. Hopefully we'll do it every week :+1:

**Comment by cmauban** [comment]
Don't worry, you're not alone! I feel the same way. Keep it up :+1:

**Comment by ericquayson** [comment]
:+1:  Terry, I can relate to this journal. Grabbing elements on the DOM makes me uncomfortable too haha. Luckily, we were introduced to a library like jQuery that can make things a little easier for us. Great job.

**Comment by cmauban** [comment]
I'm glad you're finally have moments of clarity! :+1: For your next revision, maybe connect what you have learned to one of the topics were were given, ie. MVC or encapsulation.

**Comment by s4dmw** [comment]
good read Terry. I feel the same way about getting comfortable with a concept and then having to move on...

:+1:

**Comment by jeremyrist** [comment]
Some of the language gets a little funny at times but overall I feel ya! :+1: Also there's a typo with "improvements" you might wanna correct.

**Pull request merged**
